### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_excel('/content/gdrive/My Drive/Colab Notebooks/Artificial Neural Network for regression /Dataset/Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

### Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [7]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


## Part 2 - Building the ANN

### Initializing the ANN

In [8]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [12]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [13]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 877us/step - loss: 37512.5117
Epoch 2/100
240/240 [==============================] - 0s 824us/step - loss: 773.9635
Epoch 3/100
240/240 [==============================] - 0s 918us/step - loss: 727.9570
Epoch 4/100
240/240 [==============================] - 0s 884us/step - loss: 672.5457
Epoch 5/100
240/240 [==============================] - 0s 823us/step - loss: 611.8278
Epoch 6/100
240/240 [==============================] - 0s 806us/step - loss: 548.3696
Epoch 7/100
240/240 [==============================] - 0s 824us/step - loss: 486.1671
Epoch 8/100
240/240 [==============================] - 0s 859us/step - loss: 424.0315
Epoch 9/100
240/240 [==============================] - 0s 870us/step - loss: 364.2976
Epoch 10/100
240/240 [==============================] - 0s 900us/step - loss: 307.6184
Epoch 11/100
240/240 [==============================] - 0s 895us/step - loss: 256.0100
Epoch 12/100
240/240 [============================

### Predicting the results of the Test set

In [14]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[429.43 431.23]
 [460.46 460.01]
 [463.98 461.14]
 ...
 [471.12 473.26]
 [438.18 438.  ]
 [457.27 463.28]]
